name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MySql
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: ${{ vars.DB_NAME }}
        mysql root password: ${{ secrets.DB_PASSWORD}}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run integration tests
      run: npm test
