name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Add commands to set up the MySQL database
    - name: Setup MySQL Database
      run: |
        sudo /etc/init.d/mysql start
        mysql -h 127.0.0.1 --port 3306 -u root -p'root' -e "GRANT ALL ON *.* TO 'admin'@'localhost' IDENTIFIED BY 'password' WITH GRANT OPTION;"
        mysql -h 127.0.0.1 --port 3306 -u root -p'root' -e "FLUSH PRIVILEGES;"
    - name: Setup MySql
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: ${{ secrets.DB_PASSWORD }}
        mysql database: ${{ vars.DB_NAME }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup envirornment variables
      run: |
        touch .env
        echo PORT=${{ vars.PORT }} >> .env
        echo DB_HOST=${{ vars.DB_HOST }} >> .env
        echo DB_NAME=${{ vars.DB_NAME}} >> .env
        echo DB_USER=${{ vars.DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_DIALECT=${{ vars.DB_DIALECT }} >> .env
        echo NODE_ENV=${{ vars.NODE_ENV }} >> .env


    - name: Install dependencies
      run: npm install

    - name: Run integration tests
      run: npm test
